import { Comment } from "./models/comment";

export const COMMENTS: Comment[] = [
  { cId: 1, body: 'Body Body Body Body Body Body Body Body Body Body Body Body Body Body Body Body Body Body Body Body', created: new Date(), author: 'Dr Nice', root: 11 },
  { cId: 2, body: 'Body', created: new Date(), author: 'Narco', root: 11 },
  { cId: 3, body: 'Body', created: new Date(), author: 'Bombasto', root: 11 },
  { cId: 4, body: 'Body', created: new Date(), author: 'Celeritas', root: 11 },
  { cId: 5, body: 'Body', created: new Date(), author: 'Magneta', root: 11 },
  { cId: 6, body: 'Body', created: new Date(), author: 'RubberMan', root: 11 },
  { cId: 7, body: 'Body', created: new Date(), author: 'Dynama', root: 11 },
  { cId: 8, body: 'Body', created: new Date(), author: 'Dr IQ', root: 11 },
  { cId: 9, body: 'Body', created: new Date(), author: 'Magma', root: 11 },
  { cId: 10, body: 'Body', created: new Date(), author: 'Tornado', root: 11 },

  { cId: 11, body: 'Body', created: new Date(), author: 'Dr Nice', root: 12 },
  { cId: 12, body: 'Body', created: new Date(), author: 'Narco', root: 12 },
  { cId: 13, body: 'Body', created: new Date(), author: 'Bombasto', root: 12 },
  { cId: 14, body: 'Body', created: new Date(), author: 'Celeritas', root: 12 },
  { cId: 15, body: 'Body', created: new Date(), author: 'Magneta', root: 12 },
  { cId: 16, body: 'Body', created: new Date(), author: 'RubberMan', root: 12 },
  { cId: 17, body: 'Body', created: new Date(), author: 'Dynama', root: 12 },
  { cId: 18, body: 'Body', created: new Date(), author: 'Dr IQ', root: 12 },
  { cId: 19, body: 'Body', created: new Date(), author: 'Magma', root: 12 },
  { cId: 20, body: 'Body', created: new Date(), author: 'Tornado', root: 12 },

  { cId: 21, body: 'Body', created: new Date(), author: 'Dr Nice', root: 13 },
  { cId: 22, body: 'Body', created: new Date(), author: 'Narco', root: 13 },
  { cId: 23, body: 'Body', created: new Date(), author: 'Bombasto', root: 13 },
  { cId: 24, body: 'Body', created: new Date(), author: 'Celeritas', root: 13 },
  { cId: 25, body: 'Body', created: new Date(), author: 'Magneta', root: 13 },
  { cId: 26, body: 'Body', created: new Date(), author: 'RubberMan', root: 13 },
  { cId: 27, body: 'Body', created: new Date(), author: 'Dynama', root: 13 },
  { cId: 28, body: 'Body', created: new Date(), author: 'Dr IQ', root: 13 },
  { cId: 29, body: 'Body', created: new Date(), author: 'Magma', root: 13 },
  { cId: 30, body: 'Body', created: new Date(), author: 'Tornado', root: 13 },

  { cId: 31, body: 'Body', created: new Date(), author: 'Dr Nice', root: 14 },
  { cId: 32, body: 'Body', created: new Date(), author: 'Narco', root: 14 },
  { cId: 33, body: 'Body', created: new Date(), author: 'Bombasto', root: 14 },
  { cId: 34, body: 'Body', created: new Date(), author: 'Celeritas', root: 14 },
  { cId: 35, body: 'Body', created: new Date(), author: 'Magneta', root: 14 },
  { cId: 36, body: 'Body', created: new Date(), author: 'RubberMan', root: 14 },
  { cId: 37, body: 'Body', created: new Date(), author: 'Dynama', root: 14 },
  { cId: 38, body: 'Body', created: new Date(), author: 'Dr IQ', root: 14 },
  { cId: 39, body: 'Body', created: new Date(), author: 'Magma', root: 14 },
  { cId: 40, body: 'Body', created: new Date(), author: 'Tornado', root: 14 },

  { cId: 41, body: 'Body', created: new Date(), author: 'Dr Nice', root: 15 },
  { cId: 42, body: 'Body', created: new Date(), author: 'Narco', root: 15 },
  { cId: 43, body: 'Body', created: new Date(), author: 'Bombasto', root: 15 },
  { cId: 44, body: 'Body', created: new Date(), author: 'Celeritas', root: 15 },
  { cId: 45, body: 'Body', created: new Date(), author: 'Magneta', root: 15 },
  { cId: 46, body: 'Body', created: new Date(), author: 'RubberMan', root: 15 },
  { cId: 47, body: 'Body', created: new Date(), author: 'Dynama', root: 15 },
  { cId: 48, body: 'Body', created: new Date(), author: 'Dr IQ', root: 15 },
  { cId: 49, body: 'Body', created: new Date(), author: 'Magma', root: 15 },
  { cId: 50, body: 'Body', created: new Date(), author: 'Tornado', root: 15 },

  { cId: 51, body: 'Body', created: new Date(), author: 'Dr Nice', root: 16 },
  { cId: 52, body: 'Body', created: new Date(), author: 'Narco', root: 16 },
  { cId: 53, body: 'Body', created: new Date(), author: 'Bombasto', root: 16 },
  { cId: 54, body: 'Body', created: new Date(), author: 'Celeritas', root: 16 },
  { cId: 55, body: 'Body', created: new Date(), author: 'Magneta', root: 16 },
  { cId: 56, body: 'Body', created: new Date(), author: 'RubberMan', root: 16 },
  { cId: 57, body: 'Body', created: new Date(), author: 'Dynama', root: 16 },
  { cId: 58, body: 'Body', created: new Date(), author: 'Dr IQ', root: 16 },
  { cId: 59, body: 'Body', created: new Date(), author: 'Magma', root: 16 },
  { cId: 60, body: 'Body', created: new Date(), author: 'Tornado', root: 16 },

  { cId: 61, body: 'Body', created: new Date(), author: 'Dr Nice', root: 17 },
  { cId: 62, body: 'Body', created: new Date(), author: 'Narco', root: 17 },
  { cId: 63, body: 'Body', created: new Date(), author: 'Bombasto', root: 17 },
  { cId: 64, body: 'Body', created: new Date(), author: 'Celeritas', root: 17 },
  { cId: 65, body: 'Body', created: new Date(), author: 'Magneta', root: 17 },
  { cId: 66, body: 'Body', created: new Date(), author: 'RubberMan', root: 17 },
  { cId: 67, body: 'Body', created: new Date(), author: 'Dynama', root: 17 },
  { cId: 68, body: 'Body', created: new Date(), author: 'Dr IQ', root: 17 },
  { cId: 69, body: 'Body', created: new Date(), author: 'Magma', root: 17 },
  { cId: 70, body: 'Body', created: new Date(), author: 'Tornado', root: 17 },

  { cId: 71, body: 'Body', created: new Date(), author: 'Dr Nice', root: 18 },
  { cId: 72, body: 'Body', created: new Date(), author: 'Narco', root: 18 },
  { cId: 73, body: 'Body', created: new Date(), author: 'Bombasto', root: 18 },
  { cId: 74, body: 'Body', created: new Date(), author: 'Celeritas', root: 18 },
  { cId: 75, body: 'Body', created: new Date(), author: 'Magneta', root: 18 },
  { cId: 76, body: 'Body', created: new Date(), author: 'RubberMan', root: 18 },
  { cId: 77, body: 'Body', created: new Date(), author: 'Dynama', root: 18 },
  { cId: 78, body: 'Body', created: new Date(), author: 'Dr IQ', root: 18 },
  { cId: 79, body: 'Body', created: new Date(), author: 'Magma', root: 18 },
  { cId: 80, body: 'Body', created: new Date(), author: 'Tornado', root: 18 },

  { cId: 81, body: 'Body', created: new Date(), author: 'Dr Nice', root: 19 },
  { cId: 82, body: 'Body', created: new Date(), author: 'Narco', root: 19 },
  { cId: 83, body: 'Body', created: new Date(), author: 'Bombasto', root: 19 },
  { cId: 84, body: 'Body', created: new Date(), author: 'Celeritas', root: 19 },
  { cId: 85, body: 'Body', created: new Date(), author: 'Magneta', root: 19 },
  { cId: 86, body: 'Body', created: new Date(), author: 'RubberMan', root: 19 },
  { cId: 87, body: 'Body', created: new Date(), author: 'Dynama', root: 19 },
  { cId: 88, body: 'Body', created: new Date(), author: 'Dr IQ', root: 19 },
  { cId: 89, body: 'Body', created: new Date(), author: 'Magma', root: 19 },
  { cId: 90, body: 'Body', created: new Date(), author: 'Tornado', root: 19 },

  { cId: 91, body: 'Body', created: new Date(), author: 'Dr Nice', root: 20 },
  { cId: 92, body: 'Body', created: new Date(), author: 'Narco', root: 20 },
  { cId: 93, body: 'Body', created: new Date(), author: 'Bombasto', root: 20 },
  { cId: 94, body: 'Body', created: new Date(), author: 'Celeritas', root: 20 },
  { cId: 95, body: 'Body', created: new Date(), author: 'Magneta', root: 20 },
  { cId: 96, body: 'Body', created: new Date(), author: 'RubberMan', root: 20 },
  { cId: 97, body: 'Body', created: new Date(), author: 'Dynama', root: 20 },
  { cId: 98, body: 'Body', created: new Date(), author: 'Dr IQ', root: 20 },
  { cId: 99, body: 'Body', created: new Date(), author: 'Magma', root: 20 },
  { cId: 100, body: 'Body', created: new Date(), author: 'Tornado', root: 20 }
];